/*
 * base0fs.c
 * Do not edit by hand.
 * Automatically generated by fistgen.
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif /* HAVE_CONFIG_H */
#ifdef FISTGEN
# include "fist_base0fs.h"
#endif /* FISTGEN */
#include "fist.h"
#include "base0fs.h"

/* OPTIONAL CODE FOLLOWS */

/* no extra routines are needed */


/*
 * Local variables:
 * c-basic-offset: 4
 * End:
 */
