/*
 * Do not edit by hand.
 * Automatically generated by fistgen.
 */
#ifndef _fist_base0fs_h
#define _fist_base0fs_h

/* OPTIONAL DECLARATIONS FOLLOW */


  /*
   * base0fs: like lofs, modifies neither file names nor their data
   */

/* MACROS AND STRUCTURES BASED ON FIST FILE tests/base0fs.fist */

/* Name of the file system? */
#define FIST_FSNAME "base0fs"

/* What access mode: readonly, writeonly, or readwrite? */
/* #undef FIST_ACCESSMODE_READONLY */
/* #undef FIST_ACCESSMODE_WRITEONLY */
#define FIST_ACCESSMODE_READWRITE 1

/* Turn on debugging? */
#define FIST_DEBUG 1

/* Turn on dynamic_inode_numbers? */
/* #undef FIST_DYNAMIC_INODE_NUMBERS */

/* Turn on follow_mountpoints? */
/* #undef FIST_FOLLOW_MOUNTPOINTS */

/* Manipulate file data? */
/* #undef FIST_FILTER_DATA */

/* Manipulate file names? */
/* #undef FIST_FILTER_NAME */

/* Size changing algorithm filter? */
/* #undef FIST_FILTER_SCA */

/* What mount style: regular, overlay, or attach? */
#define FIST_MNTSTYLE_REGULAR 1
/* #undef FIST_MNTSTYLE_OVERLAY */
/* #undef FIST_MNTSTYLE_ATTACH */

/* fan-out value */
#define FIST_FANOUT 1

/* What encoding type: none, stream, or block? */
/* #undef FIST_ENCODING_TYPE_NONE */
/* #undef FIST_ENCODING_TYPE_STREAM */
#define FIST_ENCODING_TYPE_BLOCK 1

/* encoding-blocksize VALUE */
#define FIST_ENCODING_BLOCKSIZE 1

/* Error codes? */
/* no error codes defined */

/* Mount flags? */
/* no error codes defined */

/* Mount data arguments? */
/* no mount data defined */

/* Per-VFS data? */
/* no per-VFS data defined */

/* Per-vnode data? */
/* no per-vnode data defined */

/* file formats */
/* using auxiliary sources? */
/* #undef FIST_USE_AUX_SRC */
/* no fileformats defined */

#endif /* not _fist_base0fs_h */
